### ISSUE TITLE
Character modularity

### ISSUE THREAD

**Issue by manderson0** [Shaumik-Ashraf/JASC#10]
Here's an idea i'm just throwing out there. How about we re-write the character skill use code as follows, instead of using what we currently have in Legendairy.java:

-There is a class called Skills.java that contains all skills and static methods for their effects. Effects are then multiplied based on character stats/level
-When a character is constructed, he has his own arraylist of owned skills, and learnable skills.
-When a characters levels to the correct level, the next learnable skill is transported to his useable skill list.
-When a character uses a skill it just checks if he owns it, and then executes the hardcoded effect in Skills.java on a designated target, with modifiers
-Stats.java will have a static hashmap of skills and their MP costs.
-MP is used when using a skill, value gotten from hashmap.

Seems better than checking for every skill manually in the main function. I can help you write it if you want.

**Comment by manderson0** [comment]
Every character has an element implementation. In every element interface there should be only 1 method: a getSkills method, that adds skills to the characters list based on the element.

**Comment by manderson0** [comment]
UML's:

SKILL.JAVA:
Public Abstract Class Skill:
-protected int mpCost;
    //All skills cost some amount of mp
-public static HashMap <String,Skill> allSkills
    //contains all skills in the game, maps skill name to skill object of same name. Stores a skill object in each slot
+public static HashMap getAllSkills
    //returns dictionary of names and skills
+public abstract void use(Character c)
    //uses skill on designated character
+public abstract int getMpCost
    //return MP cost

Class (skill name) extends Skill:
    //each skill gets its tiny little class
+public (skill name)()
    //Constructor initializes mp cost
+public void use(HashMap<String,Integer> userStats, Character c)
   //executes skill effect on character c, uses your stats to modify effects
+public int getMpCost
    //returns MP cost as int

CHANGES TO CHARACTER.JAVA:
public class Character:
-protected HashMap<String,Integer> Stats
    //character stats stored in hashmap now
-protected ArrayList<String> Learnable 
-protected ArrayList<String> Known
    //these lists only store NAMES. Skills themselves will be referenced using the skill.java hashmap, with these names as the keys
    //Arraylists for known and learnable skills
+public Character(String className, String name)
    //initializes class, name, stats, etc.
    //Based on class, calls classSkillCons() for an organized way of giving character the right skills
+public void classSkillCons (String className)
   //adds skill names to arraylists based on class. uses switch functionality
+public void useSkill (String skillName, Character c)
   //Checks if character owns skill with name skillName. If not, do nothing. If he does, do this: Skills.getAllSkills().get(skillName).use(Stats, c)

**Comment by manderson0** [comment]
Basic Attack counts as a skill, too. That actually would work well

**Comment by jcao14** [comment]
That sounds like a good idea. I'll try to implement this today.

**Comment by manderson0** [comment]
I pushed a working version of skills.java but it only has basic attack. I can modify character.java as needed as well if you want

**Comment by manderson0** [comment]
its in the ideas folder, where i copied the latest versions of gchar and legendiary

**Comment by jcao14** [comment]
I think I understand how to implement all of this. Lemme try it out by myself first. I'll let you know if I need any assistance. Thanks. :D

**Comment by manderson0** [comment]
ok. I began rewriting gchar because i have nothing better to do at the moment
maybe i should add you to my c9 workspace

**Comment by manderson0** [comment]
got teamspeak or something?

**Comment by manderson0** [comment]
actually im pretty much done LOLOLOL

**Comment by manderson0** [comment]
sorry about that

**Comment by jcao14** [comment]
Whuuuutt. Fineeee.
add me to your cloud9 workspace.
bendypeanut1

**Comment by manderson0** [comment]
added

**Comment by manderson0** [comment]
and guess what, now we dont need any seperate class files for character classes, and the code is ready for party battles
