### ISSUE TITLE
Event and Enemy Modularity

### ISSUE THREAD

**Issue by manderson0** [Shaumik-Ashraf/JASC#11]
Hey, i have begun implementing events in event.java. We should tie this in with area.java soon, and have the area spawn events based on location. Events encompass all occurrances in game, so if theres a fight it will spawn a CombatEvent. I wrote the code of CombatEvent and you can test it in GChar.

Also, we need to touch up monster.java. I was thinking we do what i did with item.java and create a hashmap of monsters with thier stats and abilities, and when they're are constructed a copy of these stats are taken based on name.

**Comment by manderson0** [comment]
whats cool about events is that you can chain them together. During a loot event, for ewxample, if youy want the party to be ambushed, you can spawn a combatevent immediately and have it resolve

**Comment by jcao14** [comment]
Should Monster be an extension of gChar or should it be implemented similarly to how each job is created?

**Comment by manderson0** [comment]
i would prefer extension. Its just gchar but with 1 skill and no inventory
