### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jcao14** [Shaumik-Ashraf/JASC#17]
Enter long number.
So I typed 1.1 and it broke the code?

**Comment by jcao14** [comment]
Also, there aren't any random monsters?

**Comment by jcao14** [comment]
Game still crashes when I die.

**Comment by Shaumik-Ashraf** [comment]
1.1 isnt a long 
longs are ints, but with a higher value range (-1*2^64 to 2^64-1, i believe)

**Comment by jcao14** [comment]
Yeah. I was just testing to see what would happen if the user did.

**Comment by manderson0** [comment]
fixed. Closing issue.
